class Laptop {
    String model;
    int price;

//    public String toString() {
//        return model + " : " + price;
//    }


    @java.lang.Override
    public java.lang.String toString() { // This is Auto Generated By IDE.
        return "Laptop{" +
                "model='" + model + '\'' +
                ", price=" + price +
                '}';
    }

    public boolean equals(Object object) { // This is Auto Generated By IDE.
        if (object == null || getClass() != object.getClass()) return false;
        if (!super.equals(object)) return false;
        Laptop laptop = (Laptop) object;
        return price == laptop.price && java.util.Objects.equals(model, laptop.model);
    }

    public int hashCode() {
        return Objects.hash(super.hashCode(), model, price);
    }
}

public class ObjectClass  {
    public static void main(String[] args) {
        Laptop obj1 = new Laptop();
        obj1.model = "Mac Book M4";
        obj1.price = 1000;

        Laptop obj2 = new Laptop();
        obj2.model = "Mac Book M4";
        obj2.price = 1000;

        System.out.println(obj1); // By default this will print Something like this -> "Laptop@2d363fb3"
        System.out.println(obj1); // But I Overridded the toString() Method from the Object class
        // By default while Printing the obj1 or obj2 above it will apply toString() function. So it will be like "obj1.toString()" or "obj2.toString()"

        System.out.println(obj1.equals(obj2));


    }
}